language: python
sudo: false
python:
  - 3.5

cache:
  directories:
    - $HOME/.cache/pip

services:
  - MySQL
  - PostgreSQL

env:
   - TOXENV=py27-d18-pg
   - TOXENV=py27-d18-sqlite
   - TOXENV=py27-d18-mysql
   - TOXENV=py27-d19-pg
   - TOXENV=py27-d19-sqlite
   - TOXENV=py27-d19-mysql
   - TOXENV=py27-d110-pg
   - TOXENV=py27-d110-sqlite
   - TOXENV=py27-d110-mysql
   - TOXENV=py27-d111-pg
   - TOXENV=py27-d111-sqlite
   - TOXENV=py27-d111-mysql

   - TOXENV=py33-d18-pg
   - TOXENV=py33-d18-sqlite

   - TOXENV=py34-d18-pg
   - TOXENV=py34-d18-sqlite
   - TOXENV=py34-d19-pg
   - TOXENV=py34-d19-sqlite

   - TOXENV=py35-d18-pg
   - TOXENV=py35-d18-sqlite
   - TOXENV=py35-d19-pg
   - TOXENV=py35-d19-sqlite
   - TOXENV=py35-d110-pg
   - TOXENV=py35-d110-sqlite
   - TOXENV=py35-d111-pg
   - TOXENV=py35-d111-sqlite

   - TOXENV=py36-d18-pg
   - TOXENV=py36-d18-sqlite
   - TOXENV=py36-d19-pg
   - TOXENV=py36-d19-sqlite
   - TOXENV=py36-d110-pg
   - TOXENV=py36-d110-sqlite
   - TOXENV=py36-d111-pg
   - TOXENV=py36-d111-sqlite

   - TOXENV=pypy-d18-pg
   - TOXENV=pypy-d18-sqlite
   - TOXENV=pypy-d19-pg
   - TOXENV=pypy-d19-sqlite

   - TOXENV=pypy-d110-pg
   - TOXENV=pypy-d110-sqlite



install:
  - pip install tox "coverage<=4.0" python-coveralls>=2.5 coveralls>=0.5 codecov

script:
  - tox -e $TOXENV -- py.test tests -v --capture=no --cov=concurrency --cov-report=xml --cov-config=tests/.coveragerc

before_success:
  - coverage erase

after_success:
  - coverage combine
  - coveralls
  - codecov


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bf3806c14c6efcff7da1
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
