language: python
services:
  - MySQL
  - PostgreSQL

env:
  - TESTENV=p27d14pg
  - TESTENV=p27d15pg
  - TESTENV=p27d16pg
  - TESTENV=p27d17pg
  - TESTENV=p27dtrunkpg
  - TESTENV=p33d16pg
  - TESTENV=p27d16mysql


install:
  - make install-deps

script:
  - make init-db
  - tox -e $TESTENV


after_success:
  - coveralls
