language: python
services:
  - MySQL
  - PostgreSQL
python:
  - 2.7
  - 3.2
env:
  - DJANGO="1.4.x" DBENGINE=mysql
  - DJANGO="1.4.x" DBENGINE=pg

  - DJANGO="1.5.x" DBENGINE=mysql
  - DJANGO="1.5.x" DBENGINE=pg

  - DJANGO="1.6.x" DBENGINE=pg
  - DJANGO="dev" DBENGINE=pg


install:
  - make install-deps
  - sh -c "if [ '$DBENGINE' = 'pg' ]; then pip install -q psycopg2; fi"
  - sh -c "if [ '$DBENGINE' = 'mysql' ]; then pip install -q MySQL-python; fi"

script:
  - make ci

before_install:
  - sh -c "if [ '$DBENGINE' = 'pg' ]; then psql -c 'DROP DATABASE IF EXISTS concurrency;' -U postgres; fi"
  - sh -c "if [ '$DBENGINE' = 'mysql' ]; then mysql -e 'DROP DATABASE IF EXISTS concurrency;'; fi"

before_script:
  - sh -c "if [ '$DBENGINE' = 'pg' ]; then psql -c 'CREATE DATABASE concurrency;' -U postgres; fi"
  - sh -c "if [ '$DBENGINE' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS concurrency;'; fi"

matrix:
  exclude:
    - python: 3.2
      env: DJANGO="1.4.x"
    - python: 3.2
      env: DJANGO="1.5.x" DBENGINE=mysql

after_success:
  - coveralls
