language: python
python:
  - "2.7"
  - "3.4"

cache:
  - pip

sudo: false

services:
  - MySQL
  - PostgreSQL

env:
  - DJANGO=1.4.x DBENGINE=pg
  - DJANGO=1.5.x DBENGINE=pg
  - DJANGO=1.6.x DBENGINE=pg
  - DJANGO=1.7.x DBENGINE=pg
  - DJANGO=1.8.x DBENGINE=pg
  - DJANGO=dev DBENGINE=pg

  - DJANGO=1.4.x DBENGINE=mysql
  - DJANGO=1.5.x DBENGINE=mysql
  - DJANGO=1.6.x DBENGINE=mysql
  - DJANGO=1.7.x DBENGINE=mysql
  - DJANGO=1.8.x DBENGINE=mysql
  - DJANGO=dev DBENGINE=pg

install:
  - pip install tox>=1.8
  - pip install python-coveralls==2.0.4 coveralls==0.3


script:
  - make coverage

before_success:
  - coverage erase

after_success:
  - coverage combine
  - coveralls

matrix:
  allow_failures:
    - env: DJANGO=dev DBENGINE=pg

  exclude:
    - python: "3.4"
      env: DJANGO=1.4.x DBENGINE=pg
    - python: "3.4"
      env: DJANGO=1.5.x DBENGINE=pg
    - python: "3.4"
      env: DJANGO=1.6.x DBENGINE=pg

    - python: "3.4"
      env: DJANGO=1.4.x DBENGINE=mysql
    - python: "3.4"
      env: DJANGO=1.5.x DBENGINE=mysql
    - python: "3.4"
      env: DJANGO=1.6.x DBENGINE=mysql
    - python: "3.4"
      env: DJANGO=1.7.x DBENGINE=mysql
    - python: "3.4"
      env: DJANGO=1.8.x DBENGINE=mysql
    - python: "3.4"
      env: DJANGO=dev DBENGINE=mysql
