language: python
python:
  - "2.7"
  - "3.4"

services:
  - MySQL
  - PostgreSQL

env:
  - TESTENV=py27-d14-pg
  - TESTENV=py27-d14-mysql
  - TESTENV=py27-d15-pg
  - TESTENV=py27-d15-mysql
  - TESTENV=py27-d16-pg
  - TESTENV=py27-d16-mysql
  - TESTENV=py27-d17-pg
  - TESTENV=py27-d17-mysql
  - TESTENV=py27-d16-mysql
  - TESTENV=py27-d18-pg
  - TESTENV=py34-d17-pg
  - TESTENV=py34-d18-pg

install:
  - pip install tox>=1.8

script:
  - tox -e $TESTENV


after_success:
  - coveralls

matrix:
  allow_failures:
    - rvm: 1.9.3
