language: python
services:
  - MySQL
  - PostgreSQL
python:
  - 2.7
  - 3.2

env:
  - DJANGO="1.4.x" DBENGINE=mysql
  - DJANGO="1.4.x" DBENGINE=pg

  - DJANGO="1.5.x" DBENGINE=mysql
  - DJANGO="1.5.x" DBENGINE=pg

  - DJANGO="1.6.x" DBENGINE=mysql
  - DJANGO="1.6.x" DBENGINE=pg

  - DJANGO="dev" DBENGINE=mysql
  - DJANGO="dev" DBENGINE=pg


install:
  - make install-deps

script:
  - make init-db ci

matrix:
  exclude:
    - python: 3.2
      env: DJANGO="1.4.x" DBENGINE=mysql
    - python: 3.2
      env: DJANGO="1.4.x" DBENGINE=pg
    - python: 3.2
      env: DJANGO="1.5.x" DBENGINE=mysql

    - python: 3.2
      env: DJANGO="1.5.x" DBENGINE=pg
    - python: 3.2
      env: DJANGO="dev" DBENGINE=mysql
    - python: 3.2
      env: DJANGO="dev" DBENGINE=pg
    - python: 3.2
      env: DJANGO="1.6.x" DBENGINE=mysql

    - python: 3.3
      env: DJANGO="1.5.x" DBENGINE=mysql
    - python: 3.3
      env: DJANGO="1.6.x" DBENGINE=mysql
    - python: 3.3
      env: DJANGO="dev" DBENGINE=mysql


after_success:
  - coveralls
