language: python
services:
  - MySQL
  - PostgreSQL

env:
  - TESTENV=py27-d14-pg
  - TESTENV=py27-d14-mysql
  - TESTENV=py27-d15-pg
  - TESTENV=py27-d15-mysql
  - TESTENV=py27-d16-pg
  - TESTENV=py27-d16-mysql
  - TESTENV=py27-d17-pg
  - TESTENV=py27-d17-mysql

install:
  - pip install tox==1.8

script:
  - tox -e $TESTENV


after_success:
  - coveralls
