language: python
sudo: false
python:
  - 3.5

cache:
  directories:
    - $HOME/.cache/pip

branches:
  only:
    - develop
    - master
    - feature/travis

services:
  - MySQL
  - PostgreSQL

env:
   - py27-d18-pg
   - py27-d18-sqlite
   - py27-d18-mysql
   - py27-d19-pg
   - py27-d19-sqlite
   - py27-d19-mysql
   - py33-d18-pg
   - py33-d18-sqlite
   - py34-d18-pg
   - py34-d18-sqlite
   - py34-d19-pg
   - py34-d19-sqlite
   - py35-d18-pg
   - py35-d18-sqlite
   - py35-d19-pg
   - py35-d19-sqlite
   - pypy-d18-pg
   - pypy-d18-sqlite
   - pypy-d19-pg
   - pypy-d19-sqlite


install:
  - pip install tox coverage python-coveralls>=2.5 coveralls>=0.5 codecov

script:
  - tox -e $TOXENV -- tests -vv --capture=no --cov=concurrency \
    --cov-report=xml --cov-config=tests/.coveragerc

before_success:
  - coverage erase

after_success:
  - coverage combine
  - coveralls
  - codecov


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bf3806c14c6efcff7da1
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
