language: python
sudo: true
python:
  - 3.5
  - 3.6

addons:
  postgresql: "9.4"

cache:
  directories:
    - $HOME/.cache/pip

services:
  - MySQL
  - PostgreSQL

jobs:
  include:
    - python: 3.7
      env: TRAVIS_PYTHON_VERSION=3.7 DJANGO=2.0 DB=mysql
      sudo: required
      dist: xenial

    - python: 3.7
      env: TRAVIS_PYTHON_VERSION=3.7 DJANGO=2.1 DB=pg
      sudo: required
      dist: xenial

    - python: 3.7
      env: TRAVIS_PYTHON_VERSION=3.7 DJANGO=2.0 DB=mysql
      sudo: required
      dist: xenial

    - python: 3.7
      env: TRAVIS_PYTHON_VERSION=3.7 DJANGO=2.1 DB=pg
      sudo: required
      dist: xenial


env:
  - DJANGO=1.10 DB=pg
  - DJANGO=1.11 DB=pg
  - DJANGO=2.0 DB=pg
  - DJANGO=2.1 DB=pg

  - DJANGO=1.10 DB=mysql
  - DJANGO=1.10 DB=mysql
  - DJANGO=2.0 DB=mysql
  - DJANGO=2.1 DB=mysql


matrix:
  exclude:
    - python: 2.7
      env: DJANGO=2.0 DB=pg

    - python: 2.7
      env: DJANGO=2.0 DB=mysql

install:
  - pip install tox "coverage<=4.0" codecov

script:
  - tox -e "py${TRAVIS_PYTHON_VERSION//.}-d${DJANGO//.}-${DB}" -- py.test tests -v

before_success:
  - coverage erase

after_success:
  - coverage combine
  - codecov


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bf3806c14c6efcff7da1
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
