language: python
python:
  - "2.7"
  - "3.4"

services:
  - MySQL
  - PostgreSQL

env:
  - DJANGO=1.4.x
  - DJANGO=1.5.x
  - DJANGO=1.6.x
  - DJANGO=1.7.x
  - DJANGO=1.8.x
  - DJANGO=dev

  - DBENGINE=pg
  - DBENGINE=mysql


install:
  - pip install tox>=1.8


script:
  - make coverage


after_success:
  - coveralls

matrix:
  allow_failures:
    - env: DJANGO=dev

  exclude:
    - python: 3.4
      env: DJANGO=1.4.x
    - python: 3.4
      env: DJANGO=1.5.x
    - python: 3.4
      env: DJANGO=1.6.x
